#pragma once

enum XACT_WAVEBANK_SOUNDS : unsigned int
{
    XACT_WAVEBANK_SOUNDS_TITLESCENE = 0,
    XACT_WAVEBANK_SOUNDS_SELECTSCENE = 1,
    XACT_WAVEBANK_SOUNDS_PLAYSCENE = 2,
    XACT_WAVEBANK_SOUNDS_GAMECLEARSCENE = 3,
    XACT_WAVEBANK_SOUNDS_GAMEOVERSCENE = 4,
};

#define XACT_WAVEBANK_SOUNDS_ENTRY_COUNT 5



enum XACT_WAVEBANK_SOUNDS_SE : unsigned int
{
    XACT_WAVEBANK_SOUNDS_BALLOONBLOWUP = 0,
    XACT_WAVEBANK_SOUNDS_BALLOONHIT = 1,
    XACT_WAVEBANK_SOUNDS_BALLOON_POP = 2,
    XACT_WAVEBANK_SOUNDS_BALLOONRELEASEAIR = 3,
    XACT_WAVEBANK_SOUNDS_CANCEL = 4,
    XACT_WAVEBANK_SOUNDS_MOVE = 5,
    XACT_WAVEBANK_SOUNDS_SELECT = 6,
    XACT_WAVEBANK_SOUNDS_STARTBUTTON = 7,
};


#define XACT_WAVEBANK_SOUNDS_ENTRY_COUNT_SE 8

